[versions]
alchemist = "24.1.9"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-incarnation-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-incarnation-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist"}
[bundles]
alchemist = ["alchemist", "alchemist-incarnation-scafi", "alchemist-swingui"]

[plugins]
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.4.10"
taskTree = "com.dorongold.task-tree:2.1.0"
